### ISSUE TITLE
weather data not loading

### ISSUE THREAD

**Issue by RDXRiasad** [darkmoonight/Rain#97] opened 2023-08-11 12:13 UTC
App can't detect my location for weather data(it has access of my location and it can access my location). I can search and add the location manually but the weather data is not that correct. 
![Screenshot_20230811-180025_Rain](https://github.com/DarkMooNight/Rain/assets/99120106/08d1a04c-cee6-44e9-9ca8-0ab8d455809e)

**Comment by Leonavichus** [comment] 2023-08-11 16:43
Hello, can you tell me have you downloaded floss or gms?

**Comment by vivadavid** [comment] 2023-09-05 08:19
> Hello, can you tell me have you downloaded floss or gms?

Hi, I found this thread trying to understand the difference between floss and gms. Could you explain this, please?

**Comment by Leonavichus** [comment] 2023-09-05 08:47
> > Hello, can you tell me have you downloaded floss or gms?
> 
> Hi, I found this thread trying to understand the difference between floss and gms. Could you explain this, please?

gms - there are google services, there are none in floss

**Comment by vivadavid** [comment] 2023-09-05 10:52
Thank you, @Leonavichus ! Getting into the specific details, how can we decide which one is best for us? Are there any funcions removed in the floss version?

**Comment by Leonavichus** [comment] 2023-09-05 10:59
> Thank you, @Leonavichus ! Getting into the specific details, how can we decide which one is best for us? Are there any funcions removed in the floss version?

The floss version is for those who do not like and do not trust Google, all google trackers have been removed.

**Comment by RDXRiasad** [comment] 2023-09-05 11:09
Where I can downlaod the floss version?

**Comment by Leonavichus** [comment] 2023-09-05 11:11
> Where I can downlaod the floss version?

https://github.com/DarkMooNight/Rain/releases/tag/v.3.4

**Comment by vivadavid** [comment] 2023-09-05 11:13
Thank you for your reply, @Leonavichus ! If the only difference concerns Google trackers, I understand that all the actual features of the app work the same.

So far, I'm just using the Google Play app, but I'll take this information into account for future reference.

**Comment by RivenSkaye** [comment] 2023-09-15 22:25
I'm having the original issue here as well, on the f-droid version

**Comment by tashijayla** [comment] 2023-09-15 23:10
The https://droidify.eu.org/ version has never been able to load the weather Data in the main page on GrapheneOS. After looking at this Fred I uninstalled that version and installed the google play version from the google play store in my google play profile on GrapheneOS and version 1.2.4 still doesn't Load weather Data even when running the google version with Google play service's and the play store. I noticed that on first app launch the app doesn't ask for the location permission and even if you Grant it the main page doesn't load. I would recommend adding a few things to the first launch dialogue.  the choice to enable AMOLED-theme and dynamic color's in supported versions of android would be amazing, and a please enable location permission dialogue for if it hasn't already been granted.

Just to be clear the city section has always worked perfectly.

Today a friend asked me what the best open source weather app is and I really wanted to suggest this but just couldn't

**Comment by RDXRiasad** [comment] 2023-09-16 16:27
okay guys i have download "RAIN" application from playstore and problem sloved.  Thanks

**Comment by LittleFreak** [comment] 2023-09-20 10:17
When this bug appears, you might try to search/Enter your location again.
As for the 2nd page, it's completely working for me in the FOSS Version

**Comment by Leonavichus** [comment] 2023-09-20 10:34
In the new version, which will be released in about a week, everything should work fine.

**Comment by Leonavichus** [comment] 2023-09-22 12:22
Can you see if everything works fine in this [version](https://github.com/DarkMooNight/Rain/releases/tag/v.3.5-beta)?

**Comment by LittleFreak** [comment] 2023-09-22 12:51
All the same for me. Searching for Berlin worked out, let's see how long it lasts, before it gets blank again ^^
Also hitting the location pin 📍 at the top left doesn't anything. Is that intended?
Thought it would search for your local weather.

Permissions are set to "allowed when app is open."

**Comment by Leonavichus** [comment] 2023-09-22 12:53
> Also hitting the location pin 📍 at the top left doesn't anything. Is that intended?

It's just an icon.

**Comment by RivenSkaye** [comment] 2023-09-22 13:09
I can confirm the latest beta floss build (ARMv8a) works after force-refreshing the main page. It now picks up my location properly at the office!

I'll give it a testrun on the way home as well to see if it grabs my location on the bus as well

**Comment by RivenSkaye** [comment] 2023-09-22 16:35
Aye, this is fine to push to stable, getting all my locations updated

**Closed** 2024-06-18 18:01 UTC
Labels: bug
